# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rdpctl < Formula
  desc "Secure Go CLI for RDP connections."
  homepage "https://github.com/kennyparsons/rdpctl"
  version "1.0.1"
  license "MIT"

  depends_on "freerdp"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kennyparsons/rdpctl/releases/download/v1.0.1/rdpctl_Darwin_x86_64.tar.gz"
      sha256 "9bc30f7824af93e7a28c964ffefbb706bb616735676f528699f39609e6f34a88"

      def install
        bin.install "rdpctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kennyparsons/rdpctl/releases/download/v1.0.1/rdpctl_Darwin_arm64.tar.gz"
      sha256 "c0a8e1aa2f215bec5d84a22324090c4908becebe0c77c9a7b8ebc7d3ec199429"

      def install
        bin.install "rdpctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kennyparsons/rdpctl/releases/download/v1.0.1/rdpctl_Linux_x86_64.tar.gz"
      sha256 "533080e6e8cfb43e3d7f353a1a6a4bbecb21a8f12680e394875b1ff8ef746d35"
      def install
        bin.install "rdpctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kennyparsons/rdpctl/releases/download/v1.0.1/rdpctl_Linux_arm64.tar.gz"
      sha256 "b189636e6e650b33b62f4171d2801353248251c10b0571cbdf3d0c6bb9addbba"
      def install
        bin.install "rdpctl"
      end
    end
  end
end
